import Head from 'next/head'
import Image from 'next/image'
import { Teko } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import dynamic from "next/dynamic";
import Photosphere from '../components/photosphere';
import { useState, createRef, useEffect, useCallback } from 'react';
import imageObject from '../components/imageObject'


const MapWithNoSSR = dynamic(() => import("../components/map"), {
  ssr: false
});

const teko = Teko({ subsets: ['latin'], weight: ['400', '700'], })

export default function Home() {
  
  // Create image state and allow it to be used by children
  const [panoramaImage, setPanoramaImage] = useState(imageObject[Math.floor(Math.random() * imageObject.length)])
  const [markerLocation, setMarkerLocation] = useState(null)
  const [answerLocation, setAnswerLocation] = useState(null)
  const [totalScore, setTotalScore] = useState(0)
  const wrapperSetPanoramaImage = useCallback(val => {
    setPanoramaImage(val);
  }, [setPanoramaImage]);
  const wrapperSetMarkerLocation = useCallback(val => {
    setMarkerLocation(val);
  }, [setMarkerLocation]);
  const wrapperSetAnswerLocation = useCallback(val => {
    setAnswerLocation(val);
  }, [setAnswerLocation]);
  const wrapperSetTotalScore = useCallback(val => {
    setTotalScore(val);
  }, [setTotalScore]);


  return (
    <>
      <Head>
        <title>CyberGuessr</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${teko.className}`}>

        <div className={styles.scoreBox}>
          <p>TOTAL SCORE: {totalScore}</p>
        </div>
        
        <MapWithNoSSR 
          imageObject={imageObject} 
          setPanoramaImage={wrapperSetPanoramaImage} 
          panoramaImage={panoramaImage}
          setMarkerLocation={wrapperSetMarkerLocation}
          markerLocation={markerLocation}
          answerLocation={answerLocation}
          setAnswerLocation={wrapperSetAnswerLocation}
          totalScore={totalScore}
          setTotalScore={wrapperSetTotalScore}  />
        <Photosphere 
          imageObject={imageObject} 
          panoramaImage={panoramaImage}
          answerLocation={answerLocation}/>
      </main>

    </>
  )
}
