import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import dynamic from "next/dynamic";
import Photosphere from '../components/photosphere';
import { useState, createRef, useEffect, useCallback } from 'react';
import imageObject from '../components/imageObject'


const MapWithNoSSR = dynamic(() => import("../components/map"), {
  ssr: false
});

const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  // Create image state and allow it to be used by children
  const [panoramaImage, setPanoramaImage] = useState(imageObject[Math.floor(Math.random() * imageObject.length)])
  const [markerLocation, setMarkerLocation] = useState(null)
  const wrapperSetPanoramaImage = useCallback(val => {
    setPanoramaImage(val);
  }, [setPanoramaImage]);
  const wrapperSetMarkerLocation = useCallback(val => {
    setMarkerLocation(val);
  }, [setMarkerLocation]);


  return (
    <>
      <Head>
        <title>CyberGuessr</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        
        <MapWithNoSSR 
          imageObject={imageObject} 
          setPanoramaImage={wrapperSetPanoramaImage} 
          panoramaImage={panoramaImage}
          setMarkerLocation={wrapperSetMarkerLocation}
          markerLocation={markerLocation}  />
        <Photosphere 
          imageObject={imageObject} 
          panoramaImage={panoramaImage}/>
      </main>

    </>
  )
}
